### ISSUE TITLE
Please add 2FA authenticator with this script

### ISSUE THREAD

**Issue by xenstar** [akcryptoguy/vps-harden#6]
Hello

Can you please add the 2FA authenticator, so that after login to the server, it will prompt for a 2FA code from the app?

**Comment by akcryptoguy** [comment]
Thank you for this brilliant idea and the link you emailed.  I have added a choice to install Google 2FA and it is confirmed to be working in Digital Ocean with Ubuntu 16, 18, and 20.  I really appreciate your sharing your idea with me for the script.  Please let me know if it now works for you or if you encounter any trouble with it.

**Comment by xenstar** [comment]
You are most welcome.

When I want to upgrade and run the code again, I am getting this error

root@blog:~# sudo git clone https://github.com/akcryptoguy/vps-harden.git && cd vps-harden && sudo bash get-hard.sh

fatal: destination path 'vps-harden' already exists and is not an empty directory.

**Comment by akcryptoguy** [comment]
I would expect an error like that; my VPS-harden script is not designed to be run more than once on a server; the new addition will only work when you run it on your next server.  To install 2FA on your existing VPS, you'll need to follow the instructions here: https://www.vultr.com/docs/how-to-setup-two-factor-authentication-2fa-for-ssh-on-debian-9-using-google-authenticator
